import { useEffect, useState } from 'react'
import { Network, ZoomIn, ZoomOut, Maximize2, Download } from 'lucide-react'

const DIAGRAM_URL = '/api/architecture/diagram'

export default function Architecture() {
  const [loaded, setLoaded]   = useState(false)
  const [error,  setError]    = useState(false)
  const [zoom,   setZoom]     = useState(1.0)

  useEffect(() => {
    fetch(DIAGRAM_URL)
      .then(r => { if (!r.ok) throw new Error(r.status.toString()); setLoaded(true) })
      .catch(() => setError(true))
  }, [])

  function zoomIn()  { setZoom(z => Math.min(z + 0.2, 3.0)) }
  function zoomOut() { setZoom(z => Math.max(z - 0.2, 0.4)) }
  function reset()   { setZoom(1.0) }

  return (
    <div className="p-8 max-w-6xl">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-7 h-7 rounded-lg bg-indigo-600 flex items-center justify-center">
            <Network size={14} className="text-white" />
          </div>
          <span className="section-label">System Architecture</span>
        </div>
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="page-title mb-2">Pipeline Architecture Diagram</h1>
            <p className="page-sub">
              Publication-quality diagram showing all data flows, tensor shapes,
              the LDA→SBERT feedback loop, and the hybrid fusion formula. Exported at 300 DPI.
            </p>
          </div>
          <div className="flex items-center gap-2 shrink-0 mt-1">
            <button onClick={zoomOut} className="btn-ghost p-2.5" title="Zoom out"><ZoomOut size={15} /></button>
            <button onClick={reset} className="btn-ghost px-3 py-2 text-xs font-mono">{Math.round(zoom * 100)}%</button>
            <button onClick={zoomIn} className="btn-ghost p-2.5" title="Zoom in"><ZoomIn size={15} /></button>
            <a href={DIAGRAM_URL} download="architecture_diagram.png"
              className="btn-primary flex items-center gap-2 text-sm">
              <Download size={14} /> PNG
            </a>
          </div>
        </div>
      </div>

      {/* Legend */}
      <div className="grid grid-cols-3 md:grid-cols-6 gap-3 mb-6">
        {[
          { color: '#1e293b', label: 'Data input' },
          { color: '#1d4ed8', label: 'ML / LDA path' },
          { color: '#c2410c', label: 'DL / SBERT path' },
          { color: '#15803d', label: 'Hybrid fusion' },
          { color: '#7e22ce', label: 'GDELT live feed' },
          { color: '#dc2626', label: 'Feedback loop' },
        ].map(l => (
          <div key={l.label} className="bg-white border border-blue-100 rounded-xl px-3 py-2.5 flex items-center gap-2 shadow-sm">
            <div className="w-3 h-3 rounded-sm shrink-0" style={{ background: l.color }} />
            <span className="text-[11px] text-slate-600 font-medium">{l.label}</span>
          </div>
        ))}
      </div>

      {/* Key annotations */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { label: 'Tensor shapes', desc: 'Input/output dimensions annotated at every stage (e.g. (N, 384), (10, 384))', icon: '📐' },
          { label: 'Feedback arrow', desc: 'SBERT cluster confidence re-weights LDA seeds — bidirectional synergy', icon: '🔄' },
          { label: 'Fusion formula', desc: 'S_I^hybrid = (α*·SBERT_uniq + (1−α*)·LDA_rarity) × |τ| rendered in LaTeX', icon: '⚗️' },
        ].map(a => (
          <div key={a.label} className="bg-white border border-blue-100 rounded-2xl p-4 shadow-sm flex items-start gap-3">
            <span className="text-xl shrink-0">{a.icon}</span>
            <div>
              <div className="font-bold text-sm text-slate-900">{a.label}</div>
              <div className="text-[11px] text-slate-500 mt-0.5 leading-relaxed">{a.desc}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Diagram viewer */}
      <div className="bg-white border border-blue-100 rounded-2xl shadow-sm overflow-hidden">
        <div className="px-6 py-3 border-b border-blue-100 bg-blue-50/50 flex items-center justify-between">
          <span className="text-sm font-bold text-slate-900">architecture_diagram.png — 300 DPI</span>
          <span className="text-[11px] text-slate-500 font-mono">Generated by src/generate_architecture_diagram.py</span>
        </div>
        <div className="overflow-auto p-4" style={{ maxHeight: '72vh' }}>
          {error ? (
            <div className="flex flex-col items-center gap-4 py-16 text-center">
              <Network size={40} className="text-blue-200" />
              <div className="font-bold text-slate-900">Diagram not found</div>
              <div className="text-sm text-slate-500 max-w-sm">
                Generate the architecture diagram first, then refresh this page.
              </div>
              <div className="font-mono text-sm bg-blue-50 border border-blue-200 rounded-xl px-5 py-2.5 text-slate-700">
                python src/generate_architecture_diagram.py
              </div>
            </div>
          ) : (
            <div className="transition-transform duration-200 origin-top-left inline-block" style={{ transform: `scale(${zoom})` }}>
              <img
                src={`${DIAGRAM_URL}?t=${Date.now()}`}
                alt="Pipeline Architecture Diagram"
                className="max-w-full rounded-lg"
                onLoad={() => setLoaded(true)}
                onError={() => setError(true)}
                style={{ display: loaded ? 'block' : 'none' }}
              />
              {!loaded && !error && (
                <div className="flex flex-col items-center gap-3 py-16">
                  <div className="w-10 h-10 rounded-full border-2 border-blue-100 border-t-blue-600 animate-spin" />
                  <span className="text-sm text-slate-500">Loading diagram…</span>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Bottom actions */}
      <div className="mt-5 flex items-center gap-4">
        <a href={DIAGRAM_URL} download="architecture_diagram.png"
          className="btn-primary flex items-center gap-2 text-sm">
          <Download size={14} /> Download PNG (300 DPI)
        </a>
        <a href="/api/architecture/diagram"
          target="_blank" rel="noreferrer"
          className="btn-ghost flex items-center gap-2 text-sm">
          <Maximize2 size={14} /> Open full-size
        </a>
        <span className="text-xs text-slate-400 font-mono ml-auto">
          Also available as vector PDF in reports/architecture_diagram.pdf
        </span>
      </div>
    </div>
  )
}
